services:
  users:
    container_name: users
    build: ./users
    image: yovi-users:latest
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    environment:
      - MONGODB_DB=${MONGODB_DB}
      - MONGODB_URI=${MONGODB_URI}

  webapp:
    container_name: webapp
    build: ./webapp
    image: yovi-webapp:latest
    ports:
      - "80:80"
    networks:
      - monitor-net
    depends_on:
      - users

  gamey:
    container_name: gamey
    build: ./gamey
    image: yovi-gamey:latest
    ports:
      - "4000:4000"
    networks:
      - monitor-net
    restart: on-failure

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "9091:3000"
    networks:
      - monitor-net
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning

networks:
  monitor-net:
    driver: bridge
