services:
  users:
    container_name: users
    build:
      context: ./users
      dockerfile: Dockerfile
    image: yovi-users:${IMAGE_TAG}
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    environment:
      - MONGODB_DB=${MONGODB_DB}
      - MONGODB_URI=${MONGODB_URI}

  webapp:
    container_name: webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: yovi-webapp:${IMAGE_TAG}
    ports:
      - "80:80"
    networks:
      - monitor-net
    depends_on:
      - users

  gamey:
    container_name: gamey
    build:
      context: ./gamey
      dockerfile: Dockerfile
    image: yovi-gamey:${IMAGE_TAG}
    ports:
      - "4000:4000"
    networks:
      - monitor-net
    restart: on-failure

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "9091:3000"
    networks:
      - monitor-net
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning

networks:
  monitor-net:
    driver: bridge
