services:
  users:
    container_name: users
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    environment:
      - MONGODB_DB=${MONGODB_DB}
      - MONGODB_URI=${MONGODB_URI}

  webapp:
    container_name: webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - monitor-net
    depends_on:
      - users

  gamey:
    container_name: gamey
    build:
      context: ./gamey
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - monitor-net

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "9091:3000"
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
